language: go
sudo: false

go:
  - '1.13.x'
  - '1.14.x'

install: make

script:
 - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
